In [1]:
import torch
print(torch.__version__)

2.10.0+cpu


Creating Tensors


In [2]:
#using empty
torch.empty(2,3)

tensor([[-1.2484e+08,  4.3949e-41, -1.2584e+08],
        [ 4.3949e-41, -1.2585e+08,  4.3949e-41]])

In [3]:
#using omes
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [4]:
#using zeros (intialise biases)
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [5]:
#generating random elements
torch.rand(2,3)

tensor([[0.3005, 0.1482, 0.4310],
        [0.0858, 0.0103, 0.2731]])

In [6]:
#for  reproduceability use seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [7]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [8]:
#using tensors
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [9]:
#other ways
a=torch.arange(0,10,1)
print(a)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [10]:
a=torch.arange(0,10,2)
print(a)

tensor([0, 2, 4, 6, 8])


In [11]:
b=torch.linspace(0,10,3)
print(b)

tensor([ 0.,  5., 10.])


In [12]:
 c=torch.eye(5)#identity matrix
 print(c)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [13]:
d=torch.full((2,3),5)
print(d)

tensor([[5, 5, 5],
        [5, 5, 5]])


Tensor Shape


In [14]:
x=torch.tensor([[1,2,3],[5,6,7]])

In [15]:
x.shape

torch.Size([2, 3])

In [16]:
torch.empty_like(x)

tensor([[                  0, 7310593858020254331, 3616445622929465956],
        [6067809043658845494, 3905529280586200880, 6499596098862069550]])

In [17]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [18]:
#find data type
x.dtype

torch.int64

In [19]:
#create  a tensor with int values
torch.tensor([[1,2.3,4.3],[3.4,5.9,8]], dtype=torch.int64)

tensor([[1, 2, 4],
        [3, 5, 8]])

In [20]:
#with float values
torch.tensor([[1,2.3,4.3],[3.4,5.9,8]], dtype=torch.float64)

tensor([[1.0000, 2.3000, 4.3000],
        [3.4000, 5.9000, 8.0000]], dtype=torch.float64)

In [21]:
#changing of existing data type
x.to(torch.float64)

tensor([[1., 2., 3.],
        [5., 6., 7.]], dtype=torch.float64)

In [22]:
t=torch.tensor([[1,2,3],[4,5,6]])
s=torch.tensor([[1,1,9],[4,3,6]])
print(t+s)

tensor([[ 2,  3, 12],
        [ 8,  8, 12]])


In [23]:
t=torch.tensor([[1,2,3],[4,5,6]])
s=torch.tensor([[1,1,9],[4,3,6]])
print(t-s)

tensor([[ 0,  1, -6],
        [ 0,  2,  0]])


In [24]:
#finding absolute values
c=torch.tensor([[1,2.3,-3],[4,-5,6]])
torch.abs(c)

tensor([[1.0000, 2.3000, 3.0000],
        [4.0000, 5.0000, 6.0000]])

In [25]:
#negative values
c=torch.tensor([[1,2.3,-3],[4,-5,6]])
torch.neg(c)

tensor([[-1.0000, -2.3000,  3.0000],
        [-4.0000,  5.0000, -6.0000]])

In [26]:
#round,ceil,floor are basic decimal operations


**Reduction Operations:**

In [27]:
e=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)

In [28]:
#sum of all Element
print(e)
torch.sum(e)
#column wise sum
torch.sum(e,dim=0)
#row wise sum
torch.sum(e,dim=1)

tensor([[2., 8., 8.],
        [0., 4., 3.]])


tensor([18.,  7.])

In [29]:
#mean
torch.mean(e)

tensor(4.1667)

In [30]:
#max and min
torch.min(e)
torch.max(e)

tensor(8.)

In [31]:
#standard deviation
torch.std(e)



tensor(3.2506)

In [32]:
#varience
torch.var(e)

tensor(10.5667)

In [33]:
#argmin and argmin-gives the respective postion of the elemensts
torch.argmin(e)


tensor(3)

In [34]:
torch.argmax(e)

tensor(1)

# **Matrix Operations**

In [35]:
f=torch.randint(size=(2,3),low=0,high=10)
g=torch.randint(size=(3,2),low=0,high=10)

In [36]:
#matrix multiplication
torch.matmul(f,g)

tensor([[112, 104],
        [ 24,  19]])

In [37]:
#dot product
v1=torch.tensor([1,2,3])
v2=torch.tensor([3,5,7])
torch.dot(v1,v2)



tensor(34)

In [38]:
#transpose
torch.transpose(f,0,1)

tensor([[8, 4],
        [8, 1],
        [4, 0]])

In [39]:
#determinant
#torch.det(square matrix tensor )

In [40]:
#inverse
#torch.inverse(square matrix tensor )

# Comparison Operator

In [41]:
i=torch.randint(size=(2,3),low=0,high=10)
j=torch.randint(size=(2,3), low=0, high = 10)

In [42]:
print(i)
print(j)

tensor([[0, 1, 9],
        [9, 8, 0]])
tensor([[7, 0, 0],
        [9, 5, 7]])


In [43]:
#greater than
i>j

tensor([[False,  True,  True],
        [False,  True, False]])

In [44]:
#less than
i<j

tensor([[ True, False, False],
        [False, False,  True]])

In [45]:
#equal
i==j

tensor([[False, False, False],
        [ True, False, False]])

In [46]:
#not equal
i!=j

tensor([[ True,  True,  True],
        [False,  True,  True]])

# Special Function

In [47]:
k=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)

In [48]:
torch.log(k)

tensor([[1.0986, 2.1972, 1.3863],
        [  -inf, 1.6094, 1.9459]])

In [49]:
torch.exp(k)

tensor([[2.0086e+01, 8.1031e+03, 5.4598e+01],
        [1.0000e+00, 1.4841e+02, 1.0966e+03]])

In [50]:
torch.sqrt(k)

tensor([[1.7321, 3.0000, 2.0000],
        [0.0000, 2.2361, 2.6458]])

In [51]:
torch.pow(k,2)

tensor([[ 9., 81., 16.],
        [ 0., 25., 49.]])

In [52]:
#sigmoid
torch.sigmoid(k)

tensor([[0.9526, 0.9999, 0.9820],
        [0.5000, 0.9933, 0.9991]])

In [53]:
#softmax
torch.softmax(k,dim=0)

tensor([[0.9526, 0.9820, 0.0474],
        [0.0474, 0.0180, 0.9526]])

In [54]:
#relu
torch.relu(k)

tensor([[3., 9., 4.],
        [0., 5., 7.]])

# **Inplace Operator**

In [55]:
p=torch.rand(2,3)
q=torch.rand(2,3)

In [56]:
p+q

tensor([[1.5527, 0.9419, 0.7632],
        [1.2539, 0.5009, 0.8512]])

In [57]:
#p+q is stored at another location , we want to strore either in p location or q location

#store in p location
#p<--p+q
p.add_(q)

tensor([[1.5527, 0.9419, 0.7632],
        [1.2539, 0.5009, 0.8512]])

In [58]:
print(p)

tensor([[1.5527, 0.9419, 0.7632],
        [1.2539, 0.5009, 0.8512]])


In [59]:
#value stored in location p

In [60]:
q.relu_()

tensor([[0.9051, 0.5989, 0.4450],
        [0.7278, 0.4563, 0.3389]])

In [61]:
#underscore denotes inplace operations

# Copying a Tensor

In [62]:
z=torch.rand(2,3)

In [63]:
print(z)

tensor([[0.6211, 0.5530, 0.6896],
        [0.3687, 0.9053, 0.8356]])


In [64]:
#copy it in variable t
t=z.clone()


In [65]:
print(t)

tensor([[0.6211, 0.5530, 0.6896],
        [0.3687, 0.9053, 0.8356]])


In [66]:
id(z)

134706153733200

In [67]:
id(t)

134706153729920